2024-08-19T09:08:31.073237Z  INFO dora: Starting in local mode
2024-08-19T09:08:31.075712Z  INFO dora_daemon::coordinator: Connected to dora-coordinator at 127.0.0.1:53290
2024-08-19T09:09:46.059954Z  INFO run_inner{self.machine_id=}: dora_daemon::spawn: spawning: /Users/chenzi/env/miniconda3/envs/py310/bin/reasoner
2024-08-19T09:09:51.489750Z  INFO run_inner{self.machine_id=}: dora_daemon: all nodes are ready, starting dataflow `019169e6-4bc9-732f-af60-c0d4888f590c`
2024-08-19T09:11:25.262492Z  INFO run_inner{self.machine_id=}: dora_daemon: all nodes are ready, starting dataflow `019169e6-4bc9-732f-af60-c0d4888f590c`
2024-08-19T09:22:56.010115Z  INFO run_inner{self.machine_id=}: dora_daemon: node 019169e6-4bc9-732f-af60-c0d4888f590c/reasoner finished successfully
2024-08-19T09:22:56.010227Z  INFO run_inner{self.machine_id=}: dora_daemon: Dataflow `019169e6-4bc9-732f-af60-c0d4888f590c` finished on machine ``
2024-08-19T09:24:08.581942Z  INFO run_inner{self.machine_id=}: dora_daemon::spawn: spawning: /Users/chenzi/env/miniconda3/envs/py310/bin/reasoner
2024-08-19T09:24:13.203368Z  INFO run_inner{self.machine_id=}: dora_daemon: all nodes are ready, starting dataflow `019169f3-7505-7e77-b71b-6997ae511d50`
2024-08-20T01:02:20.856321Z  INFO run_inner{self.machine_id=}: dora_daemon: node 019169f3-7505-7e77-b71b-6997ae511d50/reasoner finished successfully
2024-08-20T01:02:20.856506Z  INFO run_inner{self.machine_id=}: dora_daemon: Dataflow `019169f3-7505-7e77-b71b-6997ae511d50` finished on machine ``
2024-08-20T01:17:34.718851Z  INFO run_inner{self.machine_id=}: dora_daemon::spawn: spawning: /Users/chenzi/env/miniconda3/envs/py310/bin/reasoner
2024-08-20T01:17:39.420644Z  INFO run_inner{self.machine_id=}: dora_daemon: all nodes are ready, starting dataflow `01916d5c-5a7e-75f9-bf15-18c68e2797d2`
2024-08-20T01:30:56.557690Z  INFO run_inner{self.machine_id=}: dora_daemon::spawn: spawning: /Users/chenzi/env/miniconda3/envs/py310/bin/reasoner
2024-08-20T01:31:01.210944Z  INFO run_inner{self.machine_id=}: dora_daemon: all nodes are ready, starting dataflow `01916d68-96ad-728f-bb40-00333600b3eb`
2024-08-20T01:49:41.818914Z  INFO run_inner{self.machine_id=}: dora_daemon::spawn: spawning: /Users/chenzi/env/miniconda3/envs/py310/bin/reasoner
2024-08-20T01:49:46.695489Z  INFO run_inner{self.machine_id=}: dora_daemon: all nodes are ready, starting dataflow `01916d79-c23a-72df-808d-20dce7182d5a`
2024-08-20T01:50:32.254598Z  INFO run_inner{self.machine_id=}: dora_daemon::spawn: spawning: /Users/chenzi/env/miniconda3/envs/py310/bin/reasoner
2024-08-20T01:50:37.074935Z  INFO run_inner{self.machine_id=}: dora_daemon: all nodes are ready, starting dataflow `01916d7a-873e-7464-adc4-2617ecee6ce8`
2024-08-20T01:51:05.000134Z  INFO run_inner{self.machine_id=}: dora_daemon: received destroy command -> exiting
2024-08-20T01:51:05.000379Z  WARN dora_daemon::node_communication: failed to send event to daemon

Location:
    /Users/chenzi/project/zcbc/dora/binaries/daemon/src/node_communication/mod.rs:552:26
2024-08-20T01:51:56.372558Z  INFO dora: Starting in local mode
2024-08-20T01:51:56.373013Z  INFO dora_daemon::coordinator: Connected to dora-coordinator at 127.0.0.1:53290
2024-08-20T01:52:05.819523Z  INFO run_inner{self.machine_id=}: dora_daemon::spawn: spawning: /Users/chenzi/env/miniconda3/envs/py310/bin/reasoner
2024-08-20T01:52:09.407135Z  INFO run_inner{self.machine_id=}: dora_daemon: all nodes are ready, starting dataflow `01916d7b-f4bb-7253-898b-09e5bfb09c82`
2024-08-20T02:31:48.765297Z  INFO run_inner{self.machine_id=}: dora_daemon::spawn: spawning: /Users/chenzi/env/miniconda3/envs/py310/bin/dora-echo
2024-08-20T02:31:49.274836Z  INFO run_inner{self.machine_id=}: dora_daemon: all nodes are ready, starting dataflow `01916da0-511c-7abc-bb9d-47f51e13b890`
2024-08-20T02:32:31.523094Z  INFO run_inner{self.machine_id=}: dora_daemon: all nodes are ready, starting dataflow `01916d7b-f4bb-7253-898b-09e5bfb09c82`
2024-08-20T02:32:31.523534Z  WARN dora_daemon::node_communication: failed to send NextFinishedDropTokens reply: NextDropEvents([])

Caused by:
   0: failed to send reply to node `terminal-input`
   1: failed to send DaemonReply
   2: Broken pipe (os error 32)

Location:
    binaries/daemon/src/node_communication/tcp.rs:91:14
2024-08-20T02:32:31.523423Z  WARN dora_daemon::node_communication: failed to send NextEvent reply: NextEvents([])

Caused by:
   0: failed to send reply to node `terminal-input`
   1: failed to send DaemonReply
   2: Broken pipe (os error 32)

Location:
    binaries/daemon/src/node_communication/tcp.rs:91:14
2024-08-20T02:32:36.500478Z  INFO run_inner{self.machine_id=}: dora_daemon: Dataflow `01916d7b-f4bb-7253-898b-09e5bfb09c82` finished on machine ``
2024-08-20T02:34:45.603688Z  INFO run_inner{self.machine_id=}: dora_daemon::spawn: spawning: /Users/chenzi/env/miniconda3/envs/py310/bin/reasoner
2024-08-20T02:34:50.553075Z  INFO run_inner{self.machine_id=}: dora_daemon: all nodes are ready, starting dataflow `01916da3-03e3-7908-8094-1763c3852391`
2024-08-20T02:36:09.966518Z  INFO run_inner{self.machine_id=}: dora_daemon::spawn: spawning: /Users/chenzi/env/miniconda3/envs/py310/bin/reasoner
2024-08-20T02:36:13.860476Z  INFO run_inner{self.machine_id=}: dora_daemon: all nodes are ready, starting dataflow `01916da4-4d6e-7be0-9b2a-dabaaec36b5f`
2024-08-20T07:43:08.925581Z  INFO run_inner{self.machine_id=}: dora_daemon::spawn: spawning: /Users/chenzi/env/miniconda3/envs/py310/bin/reasoner
2024-08-20T07:43:13.552514Z  INFO run_inner{self.machine_id=}: dora_daemon: all nodes are ready, starting dataflow `01916ebd-5a7d-7b9b-9844-aa6f2f411751`
2024-08-20T07:43:48.938638Z  WARN dora_daemon::node_communication: failed to send NextEvent reply: NextEvents([Timestamped { inner: Stop, timestamp: 66c44934f0487b90/60245A4B0CCE4064A70075507F6ED0AA }])

Caused by:
   0: failed to send reply to node `terminal-input`
   1: failed to send DaemonReply
   2: Broken pipe (os error 32)

Location:
    binaries/daemon/src/node_communication/tcp.rs:91:14
2024-08-20T07:43:48.938772Z  INFO run_inner{self.machine_id=}: dora_daemon: received destroy command -> exiting
2024-08-20T07:43:48.938843Z  WARN dora_daemon::node_communication: failed to send NextFinishedDropTokens reply: NextDropEvents([])

Caused by:
   0: failed to send reply to node `terminal-input`
   1: failed to send DaemonReply
   2: Broken pipe (os error 32)

Location:
    binaries/daemon/src/node_communication/tcp.rs:91:14
2024-08-20T07:43:52.337398Z  INFO dora: Starting in local mode
2024-08-20T07:43:52.339341Z  INFO dora_daemon::coordinator: Connected to dora-coordinator at 127.0.0.1:53290
2024-08-20T07:43:55.991259Z  INFO run_inner{self.machine_id=}: dora_daemon::spawn: spawning: /Users/chenzi/env/miniconda3/envs/py310/bin/reasoner
2024-08-20T07:43:59.975038Z  INFO run_inner{self.machine_id=}: dora_daemon: all nodes are ready, starting dataflow `01916ebe-1255-7296-99c3-92080850b2fa`
2024-08-20T07:44:17.970282Z  INFO run_inner{self.machine_id=}: dora_daemon: all nodes are ready, starting dataflow `01916ebe-1255-7296-99c3-92080850b2fa`
2024-08-20T07:45:45.754010Z  INFO run_inner{self.machine_id=}: dora_daemon: received destroy command -> exiting
2024-08-20T07:45:45.754271Z  WARN dora_daemon::node_communication: failed to send event to daemon

Location:
    /Users/chenzi/project/zcbc/dora/binaries/daemon/src/node_communication/mod.rs:552:26
2024-08-20T07:45:48.078785Z  INFO dora: Starting in local mode
2024-08-20T07:45:48.079650Z  INFO dora_daemon::coordinator: Connected to dora-coordinator at 127.0.0.1:53290
2024-08-20T07:49:35.220901Z  INFO run_inner{self.machine_id=}: dora_daemon::spawn: spawning: /Users/chenzi/env/miniconda3/envs/py310/bin/reasoner
2024-08-20T07:49:40.029249Z  INFO run_inner{self.machine_id=}: dora_daemon: all nodes are ready, starting dataflow `01916ec3-3f74-70eb-96bd-a86f45106080`
2024-08-20T07:52:54.147345Z  INFO run_inner{self.machine_id=}: dora_daemon: received destroy command -> exiting
2024-08-20T07:52:55.660681Z  INFO dora: Starting in local mode
2024-08-20T07:52:55.661269Z  INFO dora_daemon::coordinator: Connected to dora-coordinator at 127.0.0.1:53290
2024-08-20T07:53:58.178989Z  INFO run_inner{self.machine_id=}: dora_daemon::spawn: spawning: /Users/chenzi/env/miniconda3/envs/py310/bin/reasoner
2024-08-20T07:54:03.038637Z  INFO run_inner{self.machine_id=}: dora_daemon: all nodes are ready, starting dataflow `01916ec7-42a2-7e84-bb67-09e1aee57a75`
2024-08-20T07:58:18.204568Z  INFO run_inner{self.machine_id=}: dora_daemon: received destroy command -> exiting
2024-08-20T08:00:58.771725Z  INFO dora: Starting in local mode
2024-08-20T08:00:58.772830Z  INFO dora_daemon::coordinator: Connected to dora-coordinator at 127.0.0.1:53290
2024-08-20T08:01:01.186032Z  INFO run_inner{self.machine_id=}: dora_daemon::spawn: spawning: /Users/chenzi/env/miniconda3/envs/py310/bin/reasoner
2024-08-20T08:01:01.186658Z  INFO run_inner{self.machine_id=}: dora_daemon::spawn: spawning: /Users/chenzi/env/miniconda3/envs/py310/bin/content-evaluation
2024-08-20T08:01:07.323369Z  INFO dora_daemon::node_communication: channel disconnected before register message
2024-08-20T08:01:07.323624Z  INFO dora_daemon::node_communication: channel disconnected before register message
2024-08-20T08:01:08.500328Z  INFO run_inner{self.machine_id=}: dora_daemon: marking `reasoner` as cascading error caused by `content-evaluation`
2024-08-20T08:01:08.500424Z  INFO run_inner{self.machine_id=}: dora_daemon: Dataflow `01916ecd-b701-752e-9d5f-e1bc8b264450` finished on machine ``
2024-08-20T08:01:44.620142Z  INFO run_inner{self.machine_id=}: dora_daemon::spawn: spawning: /Users/chenzi/env/miniconda3/envs/py310/bin/reasoner
2024-08-20T08:01:44.620800Z  INFO run_inner{self.machine_id=}: dora_daemon::spawn: spawning: /Users/chenzi/env/miniconda3/envs/py310/bin/content-evaluation
2024-08-20T08:01:48.703500Z  INFO run_inner{self.machine_id=}: dora_daemon: all nodes are ready, starting dataflow `01916ece-60ab-70a9-af32-d6dfff6c8259`
2024-08-20T08:06:33.100208Z  INFO run_inner{self.machine_id=}: dora_daemon: node 01916ece-60ab-70a9-af32-d6dfff6c8259/reasoner finished successfully
2024-08-20T08:06:33.172967Z  INFO run_inner{self.machine_id=}: dora_daemon: node 01916ece-60ab-70a9-af32-d6dfff6c8259/content-evaluation finished successfully
2024-08-20T08:06:33.173053Z  INFO run_inner{self.machine_id=}: dora_daemon: Dataflow `01916ece-60ab-70a9-af32-d6dfff6c8259` finished on machine ``
