INFO:     Started server process [15643]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
ERROR:    Traceback (most recent call last):
  File "/Users/chenzi/env/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 700, in lifespan
    await receive()
  File "/Users/chenzi/env/miniconda3/lib/python3.12/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenzi/env/miniconda3/lib/python3.12/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=CancelledError()>
Traceback (most recent call last):
  File "/Users/chenzi/env/miniconda3/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/chenzi/env/miniconda3/lib/python3.12/site-packages/uvicorn/server.py", line 87, in _serve
    await self.main_loop()
  File "/Users/chenzi/env/miniconda3/lib/python3.12/site-packages/uvicorn/server.py", line 228, in main_loop
    await asyncio.sleep(0.1)
  File "/Users/chenzi/env/miniconda3/lib/python3.12/asyncio/tasks.py", line 665, in sleep
    return await future
INFO:     127.0.0.1:60302 - "GET /v1/models HTTP/1.1" 200 OK
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError
